spring:
  datasource:
    url: jdbc:mysql://localhost:3306/open_data_management_system
    username: root
    password: 5379820pol
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform:  org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true